// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MetricsClient is the client API for Metrics service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetricsClient interface {
	GetMetric(ctx context.Context, in *GetMetricRequest, opts ...grpc.CallOption) (*GetMetricResponse, error)
	PutMetric(ctx context.Context, in *PutMetricRequest, opts ...grpc.CallOption) (*PutMetricResponse, error)
	PutMetrics(ctx context.Context, opts ...grpc.CallOption) (Metrics_PutMetricsClient, error)
}

type metricsClient struct {
	cc grpc.ClientConnInterface
}

func NewMetricsClient(cc grpc.ClientConnInterface) MetricsClient {
	return &metricsClient{cc}
}

func (c *metricsClient) GetMetric(ctx context.Context, in *GetMetricRequest, opts ...grpc.CallOption) (*GetMetricResponse, error) {
	out := new(GetMetricResponse)
	err := c.cc.Invoke(ctx, "/proto.Metrics/GetMetric", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsClient) PutMetric(ctx context.Context, in *PutMetricRequest, opts ...grpc.CallOption) (*PutMetricResponse, error) {
	out := new(PutMetricResponse)
	err := c.cc.Invoke(ctx, "/proto.Metrics/PutMetric", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsClient) PutMetrics(ctx context.Context, opts ...grpc.CallOption) (Metrics_PutMetricsClient, error) {
	stream, err := c.cc.NewStream(ctx, &Metrics_ServiceDesc.Streams[0], "/proto.Metrics/PutMetrics", opts...)
	if err != nil {
		return nil, err
	}
	x := &metricsPutMetricsClient{stream}
	return x, nil
}

type Metrics_PutMetricsClient interface {
	Send(*PutMetricRequest) error
	CloseAndRecv() (*PutMetricResponse, error)
	grpc.ClientStream
}

type metricsPutMetricsClient struct {
	grpc.ClientStream
}

func (x *metricsPutMetricsClient) Send(m *PutMetricRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *metricsPutMetricsClient) CloseAndRecv() (*PutMetricResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(PutMetricResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MetricsServer is the server API for Metrics service.
// All implementations must embed UnimplementedMetricsServer
// for forward compatibility
type MetricsServer interface {
	GetMetric(context.Context, *GetMetricRequest) (*GetMetricResponse, error)
	PutMetric(context.Context, *PutMetricRequest) (*PutMetricResponse, error)
	PutMetrics(Metrics_PutMetricsServer) error
	mustEmbedUnimplementedMetricsServer()
}

// UnimplementedMetricsServer must be embedded to have forward compatible implementations.
type UnimplementedMetricsServer struct {
}

func (UnimplementedMetricsServer) GetMetric(context.Context, *GetMetricRequest) (*GetMetricResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetric not implemented")
}
func (UnimplementedMetricsServer) PutMetric(context.Context, *PutMetricRequest) (*PutMetricResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutMetric not implemented")
}
func (UnimplementedMetricsServer) PutMetrics(Metrics_PutMetricsServer) error {
	return status.Errorf(codes.Unimplemented, "method PutMetrics not implemented")
}
func (UnimplementedMetricsServer) mustEmbedUnimplementedMetricsServer() {}

// UnsafeMetricsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetricsServer will
// result in compilation errors.
type UnsafeMetricsServer interface {
	mustEmbedUnimplementedMetricsServer()
}

func RegisterMetricsServer(s grpc.ServiceRegistrar, srv MetricsServer) {
	s.RegisterService(&Metrics_ServiceDesc, srv)
}

func _Metrics_GetMetric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetricRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServer).GetMetric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Metrics/GetMetric",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServer).GetMetric(ctx, req.(*GetMetricRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metrics_PutMetric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutMetricRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServer).PutMetric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Metrics/PutMetric",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServer).PutMetric(ctx, req.(*PutMetricRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metrics_PutMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MetricsServer).PutMetrics(&metricsPutMetricsServer{stream})
}

type Metrics_PutMetricsServer interface {
	SendAndClose(*PutMetricResponse) error
	Recv() (*PutMetricRequest, error)
	grpc.ServerStream
}

type metricsPutMetricsServer struct {
	grpc.ServerStream
}

func (x *metricsPutMetricsServer) SendAndClose(m *PutMetricResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *metricsPutMetricsServer) Recv() (*PutMetricRequest, error) {
	m := new(PutMetricRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Metrics_ServiceDesc is the grpc.ServiceDesc for Metrics service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Metrics_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Metrics",
	HandlerType: (*MetricsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMetric",
			Handler:    _Metrics_GetMetric_Handler,
		},
		{
			MethodName: "PutMetric",
			Handler:    _Metrics_PutMetric_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PutMetrics",
			Handler:       _Metrics_PutMetrics_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "internal/proto/metrics.proto",
}
